app = "lighthouse-tracker"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  VITE_API_URL = "https://lighthouse-tracker.fly.dev"
  FREE_PLAN_MAX_DOMAINS=1
  FREE_PLAN_MAX_URLS=3
  PRO_PLAN_MAX_DOMAINS=5
  PRO_PLAN_MAX_URLS=10
  PRO_PLUS_PLAN_MAX_DOMAINS=100
  PRO_PLUS_PLAN_MAX_URLS=20
  CHROME_PATH = "/usr/bin/chromium-browser"
  CHROME_BIN = "/usr/bin/chromium-browser"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"] 